apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: stateset-sequencer
  namespace: sequencer
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: stateset-sequencer
