apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: stateset-sequencer
  namespace: sequencer
  labels:
    app.kubernetes.io/name: stateset-sequencer
    app.kubernetes.io/part-of: stateset
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: stateset-sequencer
      app.kubernetes.io/part-of: stateset
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      timeout: 10s
      authorization:
        type: ApiKey
        credentials:
          secret:
            name: sequencer-secrets
            key: BOOTSTRAP_ADMIN_API_KEY

