// This file is @generated by prost-build.
/// Tenant identifier
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TenantId {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
/// Store identifier
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StoreId {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
/// Agent identifier
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentId {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
/// Event envelope for ingestion
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventEnvelope {
    /// Unique event identifier (UUIDv4)
    #[prost(string, tag = "1")]
    pub event_id: ::prost::alloc::string::String,
    /// Optional command ID for idempotency
    #[prost(string, tag = "2")]
    pub command_id: ::prost::alloc::string::String,
    /// Tenant context
    #[prost(string, tag = "3")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub store_id: ::prost::alloc::string::String,
    /// Entity being affected
    #[prost(string, tag = "5")]
    pub entity_type: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub entity_id: ::prost::alloc::string::String,
    /// Event details
    #[prost(string, tag = "7")]
    pub event_type: ::prost::alloc::string::String,
    /// JSON payload
    #[prost(bytes = "vec", tag = "8")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// SHA-256 hash of canonical JSON payload
    #[prost(bytes = "vec", tag = "9")]
    pub payload_hash: ::prost::alloc::vec::Vec<u8>,
    /// Expected entity version (optimistic concurrency)
    #[prost(uint64, tag = "10")]
    pub base_version: u64,
    /// Event creation timestamp
    #[prost(message, optional, tag = "11")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// Source agent
    #[prost(string, tag = "12")]
    pub source_agent: ::prost::alloc::string::String,
    /// Optional cryptographic signature
    #[prost(bytes = "vec", tag = "13")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
/// Sequenced event (after ordering)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SequencedEvent {
    /// Original event envelope
    #[prost(message, optional, tag = "1")]
    pub envelope: ::core::option::Option<EventEnvelope>,
    /// Assigned global sequence number
    #[prost(uint64, tag = "2")]
    pub sequence_number: u64,
    /// When the sequencer assigned the sequence number
    #[prost(message, optional, tag = "3")]
    pub sequenced_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Rejection details for failed events
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RejectedEvent {
    /// Original event ID
    #[prost(string, tag = "1")]
    pub event_id: ::prost::alloc::string::String,
    /// Rejection reason code
    #[prost(string, tag = "2")]
    pub reason_code: ::prost::alloc::string::String,
    /// Human-readable message
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// Merkle inclusion proof
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InclusionProof {
    /// Merkle root hash
    #[prost(bytes = "vec", tag = "1")]
    pub merkle_root: ::prost::alloc::vec::Vec<u8>,
    /// Leaf index
    #[prost(uint64, tag = "2")]
    pub leaf_index: u64,
    /// Proof hashes (from leaf to root)
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub proof_hashes: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Total number of leaves in the tree
    #[prost(uint64, tag = "4")]
    pub leaf_count: u64,
}
/// Batch commitment
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchCommitment {
    /// Batch ID
    #[prost(string, tag = "1")]
    pub batch_id: ::prost::alloc::string::String,
    /// Merkle root of events in batch
    #[prost(bytes = "vec", tag = "2")]
    pub merkle_root: ::prost::alloc::vec::Vec<u8>,
    /// Sequence range
    #[prost(uint64, tag = "3")]
    pub start_sequence: u64,
    #[prost(uint64, tag = "4")]
    pub end_sequence: u64,
    /// Number of events
    #[prost(uint32, tag = "5")]
    pub event_count: u32,
    /// When commitment was created
    #[prost(message, optional, tag = "6")]
    pub committed_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PushRequest {
    /// Agent submitting the batch
    #[prost(string, tag = "1")]
    pub agent_id: ::prost::alloc::string::String,
    /// Events to ingest
    #[prost(message, repeated, tag = "2")]
    pub events: ::prost::alloc::vec::Vec<EventEnvelope>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PushResponse {
    /// Unique batch identifier
    #[prost(string, tag = "1")]
    pub batch_id: ::prost::alloc::string::String,
    /// Processing results
    #[prost(uint32, tag = "2")]
    pub events_accepted: u32,
    #[prost(message, repeated, tag = "3")]
    pub events_rejected: ::prost::alloc::vec::Vec<RejectedEvent>,
    /// Assigned sequence range (if events accepted)
    #[prost(uint64, tag = "4")]
    pub assigned_sequence_start: u64,
    #[prost(uint64, tag = "5")]
    pub assigned_sequence_end: u64,
    /// Current head after processing
    #[prost(uint64, tag = "6")]
    pub head_sequence: u64,
    /// Batch commitment (computed immediately)
    #[prost(message, optional, tag = "7")]
    pub commitment: ::core::option::Option<BatchCommitment>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PullRequest {
    /// Tenant/store context
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub store_id: ::prost::alloc::string::String,
    /// Starting cursor (sequence number)
    #[prost(uint64, tag = "3")]
    pub from_sequence: u64,
    /// Maximum events per response chunk
    #[prost(uint32, tag = "4")]
    pub batch_size: u32,
    /// Optional: filter by entity type
    #[prost(string, tag = "5")]
    pub entity_type_filter: ::prost::alloc::string::String,
    /// Optional: filter by entity ID
    #[prost(string, tag = "6")]
    pub entity_id_filter: ::prost::alloc::string::String,
    /// Whether to wait for new events (long-poll mode)
    #[prost(bool, tag = "7")]
    pub wait_for_new: bool,
    /// Maximum wait time in milliseconds (for wait_for_new)
    #[prost(uint32, tag = "8")]
    pub wait_timeout_ms: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PullResponse {
    /// Batch of sequenced events
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<SequencedEvent>,
    /// Cursor for next pull
    #[prost(uint64, tag = "2")]
    pub next_sequence: u64,
    /// Whether more events are available immediately
    #[prost(bool, tag = "3")]
    pub has_more: bool,
    /// Current head sequence
    #[prost(uint64, tag = "4")]
    pub head_sequence: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetHeadRequest {
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub store_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetHeadResponse {
    /// Current head sequence number
    #[prost(uint64, tag = "1")]
    pub head_sequence: u64,
    /// Latest commitment (if available)
    #[prost(message, optional, tag = "2")]
    pub latest_commitment: ::core::option::Option<BatchCommitment>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetInclusionProofRequest {
    /// Batch ID containing the event
    #[prost(string, tag = "1")]
    pub batch_id: ::prost::alloc::string::String,
    /// Event ID to prove
    #[prost(string, tag = "2")]
    pub event_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetInclusionProofResponse {
    /// The event being proved
    #[prost(message, optional, tag = "1")]
    pub event: ::core::option::Option<SequencedEvent>,
    /// Merkle inclusion proof
    #[prost(message, optional, tag = "2")]
    pub proof: ::core::option::Option<InclusionProof>,
    /// Batch commitment
    #[prost(message, optional, tag = "3")]
    pub commitment: ::core::option::Option<BatchCommitment>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCommitmentRequest {
    /// Batch ID
    #[prost(string, tag = "1")]
    pub batch_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCommitmentResponse {
    #[prost(message, optional, tag = "1")]
    pub commitment: ::core::option::Option<BatchCommitment>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetEntityHistoryRequest {
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub store_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub entity_type: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub entity_id: ::prost::alloc::string::String,
    /// Optional version range
    #[prost(uint64, tag = "5")]
    pub from_version: u64,
    #[prost(uint64, tag = "6")]
    pub to_version: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetEntityHistoryResponse {
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<SequencedEvent>,
    #[prost(uint64, tag = "2")]
    pub current_version: u64,
}
/// Generated client implementations.
pub mod sequencer_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// The Sequencer service provides verifiable event sync operations
    #[derive(Debug, Clone)]
    pub struct SequencerClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl SequencerClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> SequencerClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> SequencerClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            SequencerClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Push a batch of events for sequencing
        pub async fn push(
            &mut self,
            request: impl tonic::IntoRequest<super::PushRequest>,
        ) -> std::result::Result<tonic::Response<super::PushResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.sequencer.v1.Sequencer/Push",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("stateset.sequencer.v1.Sequencer", "Push"));
            self.inner.unary(req, path, codec).await
        }
        /// Pull events starting from a cursor (streaming)
        pub async fn pull(
            &mut self,
            request: impl tonic::IntoRequest<super::PullRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::PullResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.sequencer.v1.Sequencer/Pull",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("stateset.sequencer.v1.Sequencer", "Pull"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Get the current head sequence number
        pub async fn get_head(
            &mut self,
            request: impl tonic::IntoRequest<super::GetHeadRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetHeadResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.sequencer.v1.Sequencer/GetHead",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("stateset.sequencer.v1.Sequencer", "GetHead"));
            self.inner.unary(req, path, codec).await
        }
        /// Get Merkle inclusion proof for an event
        pub async fn get_inclusion_proof(
            &mut self,
            request: impl tonic::IntoRequest<super::GetInclusionProofRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetInclusionProofResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.sequencer.v1.Sequencer/GetInclusionProof",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.sequencer.v1.Sequencer",
                        "GetInclusionProof",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get a batch commitment by ID
        pub async fn get_commitment(
            &mut self,
            request: impl tonic::IntoRequest<super::GetCommitmentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetCommitmentResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.sequencer.v1.Sequencer/GetCommitment",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("stateset.sequencer.v1.Sequencer", "GetCommitment"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get entity event history
        pub async fn get_entity_history(
            &mut self,
            request: impl tonic::IntoRequest<super::GetEntityHistoryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetEntityHistoryResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/stateset.sequencer.v1.Sequencer/GetEntityHistory",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "stateset.sequencer.v1.Sequencer",
                        "GetEntityHistory",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod sequencer_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with SequencerServer.
    #[async_trait]
    pub trait Sequencer: std::marker::Send + std::marker::Sync + 'static {
        /// Push a batch of events for sequencing
        async fn push(
            &self,
            request: tonic::Request<super::PushRequest>,
        ) -> std::result::Result<tonic::Response<super::PushResponse>, tonic::Status>;
        /// Server streaming response type for the Pull method.
        type PullStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::PullResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Pull events starting from a cursor (streaming)
        async fn pull(
            &self,
            request: tonic::Request<super::PullRequest>,
        ) -> std::result::Result<tonic::Response<Self::PullStream>, tonic::Status>;
        /// Get the current head sequence number
        async fn get_head(
            &self,
            request: tonic::Request<super::GetHeadRequest>,
        ) -> std::result::Result<tonic::Response<super::GetHeadResponse>, tonic::Status>;
        /// Get Merkle inclusion proof for an event
        async fn get_inclusion_proof(
            &self,
            request: tonic::Request<super::GetInclusionProofRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetInclusionProofResponse>,
            tonic::Status,
        >;
        /// Get a batch commitment by ID
        async fn get_commitment(
            &self,
            request: tonic::Request<super::GetCommitmentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetCommitmentResponse>,
            tonic::Status,
        >;
        /// Get entity event history
        async fn get_entity_history(
            &self,
            request: tonic::Request<super::GetEntityHistoryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetEntityHistoryResponse>,
            tonic::Status,
        >;
    }
    /// The Sequencer service provides verifiable event sync operations
    #[derive(Debug)]
    pub struct SequencerServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> SequencerServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for SequencerServer<T>
    where
        T: Sequencer,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/stateset.sequencer.v1.Sequencer/Push" => {
                    #[allow(non_camel_case_types)]
                    struct PushSvc<T: Sequencer>(pub Arc<T>);
                    impl<T: Sequencer> tonic::server::UnaryService<super::PushRequest>
                    for PushSvc<T> {
                        type Response = super::PushResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PushRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Sequencer>::push(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PushSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/stateset.sequencer.v1.Sequencer/Pull" => {
                    #[allow(non_camel_case_types)]
                    struct PullSvc<T: Sequencer>(pub Arc<T>);
                    impl<
                        T: Sequencer,
                    > tonic::server::ServerStreamingService<super::PullRequest>
                    for PullSvc<T> {
                        type Response = super::PullResponse;
                        type ResponseStream = T::PullStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PullRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Sequencer>::pull(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PullSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/stateset.sequencer.v1.Sequencer/GetHead" => {
                    #[allow(non_camel_case_types)]
                    struct GetHeadSvc<T: Sequencer>(pub Arc<T>);
                    impl<T: Sequencer> tonic::server::UnaryService<super::GetHeadRequest>
                    for GetHeadSvc<T> {
                        type Response = super::GetHeadResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetHeadRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Sequencer>::get_head(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetHeadSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/stateset.sequencer.v1.Sequencer/GetInclusionProof" => {
                    #[allow(non_camel_case_types)]
                    struct GetInclusionProofSvc<T: Sequencer>(pub Arc<T>);
                    impl<
                        T: Sequencer,
                    > tonic::server::UnaryService<super::GetInclusionProofRequest>
                    for GetInclusionProofSvc<T> {
                        type Response = super::GetInclusionProofResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetInclusionProofRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Sequencer>::get_inclusion_proof(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetInclusionProofSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/stateset.sequencer.v1.Sequencer/GetCommitment" => {
                    #[allow(non_camel_case_types)]
                    struct GetCommitmentSvc<T: Sequencer>(pub Arc<T>);
                    impl<
                        T: Sequencer,
                    > tonic::server::UnaryService<super::GetCommitmentRequest>
                    for GetCommitmentSvc<T> {
                        type Response = super::GetCommitmentResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetCommitmentRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Sequencer>::get_commitment(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetCommitmentSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/stateset.sequencer.v1.Sequencer/GetEntityHistory" => {
                    #[allow(non_camel_case_types)]
                    struct GetEntityHistorySvc<T: Sequencer>(pub Arc<T>);
                    impl<
                        T: Sequencer,
                    > tonic::server::UnaryService<super::GetEntityHistoryRequest>
                    for GetEntityHistorySvc<T> {
                        type Response = super::GetEntityHistoryResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetEntityHistoryRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Sequencer>::get_entity_history(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetEntityHistorySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for SequencerServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "stateset.sequencer.v1.Sequencer";
    impl<T> tonic::server::NamedService for SequencerServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
