apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stateset-sequencer.fullname" . }}-secret
  labels:
    {{- include "stateset-sequencer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.databaseUrl }}
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.readDatabaseUrl }}
  read-database-url: {{ .Values.secrets.readDatabaseUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.bootstrapApiKey }}
  bootstrap-admin-api-key: {{ .Values.secrets.bootstrapApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.sequencerPrivateKey }}
  sequencer-private-key: {{ .Values.secrets.sequencerPrivateKey | quote }}
  {{- end }}
  {{- if .Values.secrets.l2RpcUrl }}
  l2-rpc-url: {{ .Values.secrets.l2RpcUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.setRegistryAddress }}
  set-registry-address: {{ .Values.secrets.setRegistryAddress | quote }}
  {{- end }}
  {{- if .Values.secrets.payloadEncryptionKey }}
  payload-encryption-key: {{ .Values.secrets.payloadEncryptionKey | quote }}
  {{- end }}
  {{- if .Values.secrets.vesSequencerSigningKey }}
  ves-sequencer-signing-key: {{ .Values.secrets.vesSequencerSigningKey | quote }}
  {{- end }}